name: Deploy to S3 with OIDC

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::645508719107:role/actiontestingusingoidc
          aws-region: ap-south-1
      
      - name: Run S3 Sync Action
        uses: minhaj2cloud/s3-sync-action-OIDC-Support@main
        with:
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: .
          args: --delete --exclude '.git*' --exclude '.github*'

  deploy-metadata:
    runs-on: ubuntu-latest
    needs: deploy-files
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::645508719107:role/actiontestingusingoidc
          aws-region: ap-south-1
      
      - name: Run S3 Sync Metadata Action
        uses: minhaj2cloud/s3-sync-metadata-action-OIDC-Support-@main
        with:
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          source_dir: .
          content_type: "text/html"
          exclude_pattern: "*.*"
          args: --delete --exclude '.git*' --exclude '.github*'
